/* eslint-disable max-len */
// Sentence pairs for GA6 "Embedding Auditor" (must match exam bundle `kn`).
globalThis.GA6_EMBEDDING_PAIRS = [
  ["sci_01p", "Photosynthesis converts light energy into chemical energy stored in glucose."],
  ["sci_01q", "Plants transform solar radiation into chemical bonds through photosynthesis."],
  ["sci_01r", "Photosynthesis does not produce chemical energy from light."],
  ["sci_02p", "The boiling point of water decreases at higher altitudes due to lower pressure."],
  ["sci_02q", "At elevated elevations water boils at temperatures below 100 degrees Celsius."],
  ["sci_02r", "Water boils at higher temperatures when atmospheric pressure is reduced."],
  ["sci_03p", "Neurons transmit electrical signals across synapses using neurotransmitters."],
  ["sci_03q", "Chemical messengers carry nerve impulses between brain cells at synaptic junctions."],
  ["sci_03r", "Neurons do not rely on chemical signals to communicate across gaps."],
  ["sci_04p", "Black holes have gravitational fields so strong that even light cannot escape."],
  ["sci_04q", "The escape velocity at a black hole's event horizon exceeds the speed of light."],
  ["sci_04r", "Light can escape from a black hole given sufficient velocity."],
  ["sci_05p", "DNA replication is semi-conservative: each new molecule retains one original strand."],
  ["sci_05q", "During cell division each daughter DNA helix preserves one parental strand."],
  ["sci_05r", "DNA replication produces entirely new strands without retaining any original material."],
  ["coo_01p", "Caramelization occurs when sugars are heated above their melting point."],
  ["coo_01q", "Applying high heat to sugar causes it to melt and turn brown through caramelization."],
  ["coo_01r", "Caramelization happens when sugars are kept at low temperatures."],
  ["coo_02p", "Gluten forms when flour proteins hydrate and are worked mechanically."],
  ["coo_02q", "Kneading wet flour develops gluten by cross-linking its protein strands."],
  ["coo_02r", "Gluten formation is prevented by adding water to flour."],
  ["coo_03p", "Emulsification binds oil and water using an amphiphilic agent like lecithin."],
  ["coo_03q", "An emulsifier such as egg yolk stabilizes oil-water mixtures by bridging both phases."],
  ["coo_03r", "Oil and water naturally mix without requiring an emulsifier."],
  ["coo_04p", "Sous vide cooking submerges vacuum-sealed food in a precisely temperature-controlled bath."],
  ["coo_04q", "Vacuum-packed ingredients cooked in a water bath at exact temperatures produce consistent results."],
  ["coo_04r", "Sous vide cooking requires boiling food at high temperatures."],
  ["coo_05p", "The Maillard reaction browns food by bonding amino acids with reducing sugars."],
  ["coo_05q", "Surface browning in seared meat results from a chemical reaction between proteins and sugars."],
  ["coo_05r", "The Maillard reaction requires neither amino acids nor sugars."],
  ["leg_01p", "Force majeure clauses excuse contractual obligations during unforeseeable extraordinary events."],
  ["leg_01q", "Parties may invoke force majeure to suspend duties when catastrophic unforeseen events occur."],
  ["leg_01r", "Force majeure clauses require performance even during extraordinary unforeseeable events."],
  ["leg_02p", "Indemnification requires one party to compensate another for specified losses or liabilities."],
  ["leg_02q", "Under an indemnity clause the indemnifying party covers the other's designated damages."],
  ["leg_02r", "Indemnification releases both parties from any obligation to cover losses."],
  ["leg_03p", "A non-disclosure agreement prohibits parties from sharing confidential information with third parties."],
  ["leg_03q", "NDAs legally bind signatories to keep disclosed private information secret from outsiders."],
  ["leg_03r", "A non-disclosure agreement permits unrestricted sharing of confidential information."],
  ["leg_04p", "Arbitration resolves disputes outside the court system through a neutral third-party adjudicator."],
  ["leg_04q", "Binding arbitration settles legal disagreements via an independent arbitrator rather than litigation."],
  ["leg_04r", "Arbitration requires disputes to be decided by a panel of judges in open court."],
  ["leg_05p", "A warranty guarantees that a product will perform as specified for a defined period."],
  ["leg_05q", "Manufacturers' warranties promise that goods will meet stated standards during the coverage window."],
  ["leg_05r", "A warranty places no obligation on the seller to ensure product performance."],
  ["cod_01p", "This function returns the index of the first element satisfying the predicate or -1."],
  ["cod_01q", "Searches the array sequentially and returns the position of the first matching element, else -1."],
  ["cod_01r", "This function raises an exception when no element matches the predicate."],
  ["cod_02p", "The decorator caches the return value of the function for repeated calls with the same arguments."],
  ["cod_02q", "Memoizes the wrapped function so identical inputs reuse previously computed outputs."],
  ["cod_02r", "The decorator forces recomputation for every function call regardless of arguments."],
  ["cod_03p", "This class implements the observer pattern allowing subscribers to react to state changes."],
  ["cod_03q", "Subscribers register callbacks that are invoked whenever the observed object emits an event."],
  ["cod_03r", "This class prevents external code from reacting to internal state changes."],
  ["cod_04p", "The method validates the input schema and raises a ValueError on the first violation found."],
  ["cod_04q", "Inspects incoming data against the expected schema and throws a ValueError if any field is invalid."],
  ["cod_04r", "The method silently ignores schema violations and returns the invalid input unchanged."],
  ["cod_05p", "Pagination splits large result sets into fixed-size pages to reduce memory and network load."],
  ["cod_05q", "Results are chunked into equal-sized pages enabling clients to fetch data incrementally."],
  ["cod_05r", "Pagination loads all results at once to ensure the client always has complete data."],
  ["rev_01p", "The battery life exceeded my expectations lasting nearly three days on a single charge."],
  ["rev_01q", "Impressive endurance — the device stayed powered for almost 72 hours between charges."],
  ["rev_01r", "The battery depleted in under two hours making the device practically unusable."],
  ["rev_02p", "Customer support resolved my issue promptly and the representative was knowledgeable."],
  ["rev_02q", "The support agent quickly fixed my problem demonstrating excellent product knowledge."],
  ["rev_02r", "Customer support was unable to resolve my issue and the agent lacked any product knowledge."],
  ["rev_03p", "The build quality feels premium with an all-metal chassis and satisfying haptic feedback."],
  ["rev_03q", "Solid construction and a robust metallic body give the product an upscale look and feel."],
  ["rev_03r", "The product feels cheap and plasticky with no attention paid to build quality."],
  ["rev_04p", "The learning curve was steeper than expected but the software rewards mastery."],
  ["rev_04q", "Initially difficult to use, the application becomes powerful once you invest time learning it."],
  ["rev_04r", "The software is immediately intuitive with no learning curve whatsoever."],
  ["rev_05p", "Delivery arrived two days early and the packaging kept the contents perfectly intact."],
  ["rev_05q", "The order was shipped ahead of schedule and everything was well protected on arrival."],
  ["rev_05r", "Delivery was severely delayed and the item arrived with significant packaging damage."]
];
